### PR TITLE
Refactor unit tests

### LINKED ISSUE #100: Refactor unit tests
## Feature Request

**Is your feature request related to a problem? Please describe.**
The tests are largely a mess, and they should be refactored to smaller units.

**Describe the solution you'd like**
* split the tests so that they test a single aspect
* recycle testing code as much as possible

**Describe any changes to existing user workflow**
This would make adding new tests and feature much easier.

**Additional context**
This should probably be the next step before anything new is added.

### PR DESCRIPTION
**Pull request by pnuu**
This PR will eventually refactor all the unit tests.

 - [x] Closes #100  
 - [x] Tests added

### CODE REVIEW

**Comment by pnuu** [comment]
So far tests for `trollmoves.client` have been mostly handled. I think the fixtures and such should maybe be located somewhere else.

**Comment by pnuu** [comment]
The Server tests are now refactored.

**Comment by pnuu** [comment]
Ok, all the tests have been refactored. Comments are wellcome.

**Comment by mraspaud** [comment]
The title of this PR should maybe be changed to reflect that server tests have also been refactored?

**Review by mraspaud — APPROVED** [review]
This is a huge job, thanks a lot for doing this @pnuu! I haven't look at the details, but I trust you run the tests regularly, so LGTM

**Comment by pnuu** [comment]
> The title of this PR should maybe be changed to reflect that server tests have also been refactored?

Ah, forgot to adjust after the initial commit, which ended up also as the title. Adjusted.

**Comment by pnuu** [comment]
There are couple of open questions that I forgot to write yesterday:

- should the fixtures etc. helper functions be moved from the actual test files to other files?
- should the tests in `test_ssh_server.py` be moved from the test class to separate functions and use fixtures to make the tests consistent?

**Comment by mraspaud** [comment]
> There are couple of open questions that I forgot to write yesterday:
> 
>     * should the fixtures etc. helper functions be moved from the actual test files to other files?

As long as they are just used in one place, and they are not taking all the space, I think keeping them close to where they are used is fine

>     * should the tests in `test_ssh_server.py` be moved from the test class to separate functions and use fixtures to make the tests consistent?

If it helps readability/maintainability, otherwise it's fine as it is.

**Comment by pnuu** [comment]
Ok, then I'll just leave them as they are now, and wait if @adybbroe or @TAlonglong have any comments.

**Pull request merged**
