### PR TITLE
Update python CI versions to cover 3.10 - 3.12

### PR DESCRIPTION
**Pull request by pnuu**
Update CI Python versions to 3.10, 3.11 and 3.12.

### CODE REVIEW

**Comment by pnuu** [comment]
Ok, next hurdle is `pyinotify` which uses `asyncore` that is not available in 3.12 stdlib. There is an [external package](https://github.com/simonrob/pyasyncore) supplying this, but I think migrating to `watchdog` is the way to go. I'll create another issue about this.

**Comment by pnuu** [comment]
https://github.com/pytroll/trollmoves/issues/192

**Comment by pnuu** [comment]
In short about test failures: https://github.com/pytroll/trollmoves/pull/185  needs to be merged before we can start testing on Python 3.12.

**Review by mraspaud — APPROVED** [review]
LGTM!

**Pull request merged**
