### PR TITLE
Make it possible to pass connection-parameters to the S3 mover

### PR DESCRIPTION
**Pull request by adybbroe**
This PR adds the possible to pass connection parameters when moving files to S3. By doing that it may be possible to specify the endpoint-url and the keys in the yaml file directly or indirectly by keeping those secret keys in a config file using profiles as described https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#using-a-configuration-file

I tried documenting this in the example dispatcher yaml file.

 - [ ] Closes #xxxx 
 - [x] Tests added  
 - [x] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

### CODE REVIEW

**Review by pnuu — COMMENTED** [review]
Any chance to:
- add a test?
- make this work with Trollmoves Server? (or does it already?)

**Comment by adybbroe** [comment]
> Any chance to:
> 
>     * add a test?
> 
>     * make this work with Trollmoves Server? (or does it already?)

Ok, thanks, yes, will try look at adding a test! Not sure about the second one, but we will see...

**Comment by mraspaud** [comment]
@pnuu  from what I see, the request manager passes its config directly to `move_it`, so it should already be supported in the move_it_server

**Review by pnuu — APPROVED** [review]
LGTM

**Pull request merged**
